name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Clone GitLab Repository
      run: |
        git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/railima/sicredi.git
        cd sicredi

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean test

    - name: Generate Allure Report
      run: mvn allure:report

    - name: Upload Allure Results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/allure-report

    - name: Deploy Allure Report
      run: |
        mkdir -p public
        cp -r target/allure-report/* public
      artifacts:
        paths:
          - public
